{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a87c6821",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import json\n",
    "#This program uses the CSV & JSON modules for reading/writing files\n",
    "class Book(object):\n",
    "    def __init__(self, id, title, author, genre, subgenre, publisher, loan = None, reserved=[]):\n",
    "        self.id = id\n",
    "        self.title = title\n",
    "        self.genre = genre\n",
    "        self.subgenre = subgenre\n",
    "        self.pulisher = publisher\n",
    "        self.loan = loan\n",
    "        self.reserved = reserved\n",
    "#Attributes of the class, includes the details from the CSV file as well as a loan attribute to show who currently has it loaned and a list of current reservations\n",
    "    \n",
    "    def scan(self):\n",
    "        return (\"ID: \" + self.id + \", Title: \" + self.title + \", Genre: \" + self.genre + \", Subgenre: \" + self.subgenre + \", Publisher: \" + self.publisher)\n",
    "#Scan function, returns all of a given books details\n",
    "    \n",
    "    def book_loan(self, member_no):\n",
    "        self.loan = member_no\n",
    "        for a in self.reserved:\n",
    "            if a == member_no:\n",
    "                self.reserved.remove(member_no)\n",
    "#Sets the loan attribute to the members ID number, and removes the member from the reservation list if they're in it\n",
    "    def book_reserved(self, member_no):\n",
    "        if self.loan != None:\n",
    "            self.reserved.append(member_no)\n",
    "            print (\"This book is currently reserved by\" + self.reserved)\n",
    "        else:\n",
    "            print (\"This book is not currently reserved\")\n",
    "#Function for book reservation alerts, when the member reaches index 0 of the reservation list it will print an alert, otherwise it will inform them of their place in the queue\n",
    "    def loan_check(self):\n",
    "        if self.loan is None:\n",
    "            return False\n",
    "        else:\n",
    "            return True\n",
    "#Checks whether a book is currently on loan, to ensure that members can't loan out books that aren't available\n",
    "    def book_return(self, member_no):\n",
    "        self.loan = None\n",
    "#Returns the loan attribue back to None\n",
    "\n",
    "class Member(object):\n",
    "    def __init__(self, id, fname, sname, gender, email, card, loanedbooks=[]):\n",
    "        self.id = id\n",
    "        self.fname = fname\n",
    "        self.sname = sname\n",
    "        self.gender = gender\n",
    "        self.email = email\n",
    "        self.card = card\n",
    "        self.loanedbooks = loanedbooks\n",
    "#Attributes of the class, includes the details from the CSV file and a list for books the member has loaned        \n",
    "    \n",
    "    def scan(self):\n",
    "        return (\"id: \" + self.id + \", First Name: \" + self.fname + \", Second Name: \" + self.sname + \", Gender: \" + self.gender + \", Email: \" + self.email  +\", Card Number: \" + self.card)\n",
    "#Scan function for members, returns members personal details   \n",
    "    \n",
    "    def book_loan(self, bookid):\n",
    "        self.loanedbooks.append(bookid)\n",
    "#Function for loaning books, adds the book ID to the members loaned books list\n",
    "    \n",
    "    def book_return(self, bookid):\n",
    "        self.loanedbooks.remove(bookid)\n",
    "#Function for returning books, removes the book ID from the members loaned books list\n",
    "\n",
    "def readcsv(file, type):\n",
    "    instancelist = []\n",
    "    with open(file, newline=\"\") as csvfile:\n",
    "        read = csv.reader(csvfile, delimiter = \",\", quotechar=\"\\\"\")\n",
    "        next(read)\n",
    "        for row in read:\n",
    "            if type == \"Book\":\n",
    "                instance = Book(*row)\n",
    "            elif type == \"Member\":\n",
    "                instance = Member(*row)\n",
    "            else:\n",
    "                exit()\n",
    "            instancelist.append(instance)\n",
    "    return instancelist\n",
    "#Function to read CSV files that returns a list of books or members\n",
    "\n",
    "def jsonwrite(file, booklist, memberlist):\n",
    "    dict = {\"Books\":booklist, \"Members\":memberlist}\n",
    "    with open(file, \"w\") as f:\n",
    "        json.dump(dict, f, default = vars)\n",
    "#Function to write to JSON        \n",
    "        \n",
    "def jsonread(file):\n",
    "    with open(file, \"r\") as f:\n",
    "        load = json.load(f)\n",
    "    booklist = []\n",
    "    memberlist = []\n",
    "    \n",
    "    for instance in load[\"Books\"]:\n",
    "        newbook = Book(**instance)\n",
    "        booklist.append(newbook)\n",
    "        \n",
    "    for instance in load[\"Members\"]:\n",
    "        newmember = Member(**instance)\n",
    "        memberlist.append(newmember)  \n",
    "        \n",
    "    return booklist, memberlist\n",
    "#Function to Read from JSON files, requires the file name\n",
    "\n",
    "def create_member():\n",
    "    id = input(\"ID: \")\n",
    "    fname = input(\"Please enter firstname: \")\n",
    "    sname = input(\"Please enter second name: \")\n",
    "    gender = input(\"Please enter gender: \")\n",
    "    email = input(\"Please enter email: \")\n",
    "    return Member(id, fname, sname, gender, email, int(id)*10+1)\n",
    "#Function to create new membership applications, appends the new member to the members list when run\n",
    "\n",
    "def sendemail(bookid, memberid):\n",
    "    position = bookid.reservations.index(str(memberid))\n",
    "    if position == 0:\n",
    "        print (\"This book is now available to be loaned\")\n",
    "    else:\n",
    "        print(\"You a currently number %d in the reservation queue for this book\" % (position))\n",
    "#Function for sending updates on reservations\n",
    "\n",
    "def library():\n",
    "#This function requires the user to input the relevant data for the task they've decided: \n",
    "#Loaning and returning books require their member and book IDs\n",
    "#Creating new members requires the personal information\n",
    "#Saving a JSON requires a file name.\n",
    "#Loaning and returning a book updates the relevant lists assigned in the book and member classes, \n",
    "#These changes are saved to the JSON file once option 4 is selected\n",
    "    read = None\n",
    "    while(read not in [\"1\", \"2\"]):\n",
    "        read = input(\"Press 1 to load a CSV or 2 to load a JSON\")\n",
    "        if read == \"1\":\n",
    "            bookfile = input(\"Enter book filename\")\n",
    "            try:\n",
    "                books = readcsv(bookfile, \"Book\")\n",
    "            except FileNotFoundError:\n",
    "                print (\"This file doesn't exist\")\n",
    "                read = None\n",
    "                continue\n",
    "            memberfile = input(\"Enter member file name\")\n",
    "            try:\n",
    "                members = readcsv(memberfile, \"Member\")\n",
    "            except FileNotFoundError:\n",
    "                print (\"This file doesn't exist\")\n",
    "                read = None\n",
    "                continue\n",
    "        elif read ==\"2\":\n",
    "            jsonfile = input(\"Enter filename\")\n",
    "            try:\n",
    "                books, members = jsonread(jsonfile)\n",
    "            except FileNotFoundError:\n",
    "                print (\"This file doesn't exist\")\n",
    "                read = None\n",
    "                continue\n",
    "        else:\n",
    "            print(\"This isn't supported\")\n",
    "#Prompts users to enter a file to read from\n",
    "#If CSV is selected it will ask for a book and a member file\n",
    "#If JSON is selected it will ask for one file as all data is saved to a single file\n",
    "    finished = False\n",
    "        \n",
    "    while not finished:\n",
    "        function = input(\"Press 1 to loan a book, 2 to return a book, 3 to apply for a membership or 4 to save and exit\")\n",
    "        if function ==\"1\":\n",
    "            bookid = input(\"Please enter the book ID\")\n",
    "            memberid = input(\"Please enter your member ID\")\n",
    "            tempbooks = [a for a in range(len(books)) if books[a].id ==bookid]\n",
    "            tempmembers = [a for a in range(len(members)) if members[a].id == memberid]\n",
    "            if (len(tempbooks) == 0):\n",
    "                print(\"This book doesn't exist\")\n",
    "                continue\n",
    "            elif (len(tempmembers) == 0):\n",
    "                print(\"This member ID doesn't exist\")\n",
    "                continue\n",
    "            elif not books[tempbooks[0]].loan_check():\n",
    "                books[tempbooks[0]].book_loan(memberid)\n",
    "                members[tempmembers[0]].book_loan(bookid)\n",
    "                print(\"Book has been loaned\")\n",
    "            else:\n",
    "                print(\"This book is currently on loan, you have been added to the reservation list\")\n",
    "                books[tempbooks[0]].reserved.append(memberid)\n",
    "#The main function for loaning books, requires the member and book ID number and will update the relevant lists when run \n",
    "        elif function == \"2\":\n",
    "            bookid = input(\"Please enter the book ID\")\n",
    "            memberid = input(\"Please enter your member ID\")\n",
    "            tempbooks = [a for a in range(len(books)) if books[a].id ==bookid]\n",
    "            tempmembers = [a for a in range(len(members)) if members[a].id == memberid]\n",
    "            if (len(tempbooks) == 0):\n",
    "                print(\"This book doesn't exist\")\n",
    "                continue\n",
    "            elif (len(tempmembers) == 0):\n",
    "                print(\"This member ID doesn't exist\")\n",
    "                continue\n",
    "            else:\n",
    "                books[tempbooks[0]].book_return(bookid)\n",
    "                members[tempmembers[0]].book_return(bookid)\n",
    "                print (\"Thank you for returning this book\")\n",
    "#The main function for returning books, requires the member and book ID number and will update the relevant lists when run                \n",
    "        elif function == \"3\":\n",
    "            members.append(create_member())\n",
    "#The main function for applying for membership, requires the members information and will append them to the members list when finished        \n",
    "        elif function == \"4\":\n",
    "            jsonname = input(\"Enter the name for the new JSON file\")\n",
    "            jsonwrite(jsonname, members, books)\n",
    "            finished = True\n",
    "#The main function for saving and exiting            \n",
    "library()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "49c58a10",
   "metadata": {},
   "source": [
    "The book class contains attributes for all of the books details, as well as the methods used by the program to check whether books are available, loan them and return them\n",
    "\n",
    "The member class includes all of the members details as well as methods for updating their loaned book record\n",
    "\n",
    "The create member function is used to apply for memberships, users input relevant data and the card number is worked out automatically, it appends the member list when finished\n",
    "\n",
    "The send email function prints an alert if the member is at index 0 of the reservation list, if they're not at 0 it will inform them of their position in the queue\n",
    "\n",
    "The main function lets the user choose from a variety of options, first they can choose to read from a csv or json file once this is selected they can chose from the following options; \n",
    "1)The main function for loaning books, members are prompted to enter their ID and the book ID, if the book is currently on loan they will be added to the reservation queue, if not it will be added to the users loaned books list. If the user was on the reservation list before they loaned the book they will be removed from it \n",
    "2)The main function for returning books, this will remove the book from the users loaned books list \n",
    "3)The main function for applying for memberships, this will append the members list with the details they are asked to input 4)The function to save and exit, this will prompt the user to input a new filename, save it as a JSON then exit the program"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
